name: 'Get AVD Info'
description: 'Get the Android Virtual Device (AVD) info based on its API level.'
inputs:
    api-level:
        description: The API level for which to retrieve AVD info
        required: true
outputs:
    arch:
        description: The architecture used by the AVD
        value: ${{ steps.get-avd-arch.outputs.arch }}
    target:
        description: The target location of the AVD
        value: ${{ steps.get-avd-target.outputs.target }}
runs:
    using: "composite"
    steps:
        -   id: get-avd-arch
            run: echo "::set-output name=arch::$(if [ ${{ inputs.api-level }} -ge 30 ]; then echo x86_64; else echo x86; fi)"
            shell: bash
        -   id: get-avd-target
            run: echo "::set-output name=target::$(echo default)"
            shell: bash
