name: Master

on:
    push:
        branches: [ master ]

    # Allows for running this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        timeout-minutes: 10
        outputs:
            new_tag: ${{ steps.bump_version.outputs.new_tag }}
        steps:
            -   name: Checkout the code
                uses: actions/checkout@v3

            -   name: Bump version
                id: bump_version
                uses: oflynned/Android-Semantic-Release@master
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            -   name: Create google-services.json from secrets
                env:
                    GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
                run: echo $GOOGLE_SERVICES_JSON > app/google-services.json

            -   name: Set up JDK 11
                uses: actions/setup-java@v3
                with:
                    java-version: '11'
                    distribution: 'temurin'
                    cache: gradle

            -   name: Clear gradle cache
                run: |
                    mv ~/.gradle ~/.invalid || true

            -   name: Cache dependencies
                uses: actions/cache@v3
                with:
                    path: |
                        ~/.gradle/caches
                        ~/.gradle/wrapper
                    key: ${{ runner.os }}-gradle-${{ env.CACHE_VERSION }}-${{ hashFiles('**/**.gradle.kts', '**/gradle/wrapper/gradle-wrapper.properties', '**/libs.versions.toml') }}

            -   name: Check Gradle wrapper
                uses: gradle/wrapper-validation-action@v1

            -   name: Build the app
                run: ./gradlew assembleRelease bundleRelease

            -   name: Upload unsigned APK
                uses: actions/upload-artifact@v2
                with:
                    name: release-unsigned.apk
                    path: app/build/outputs/apk/release/*.apk
                    if-no-files-found: error

            -   name: Upload unsigned AAB
                uses: actions/upload-artifact@v2
                with:
                    name: release-unsigned.aab
                    path: app/build/outputs/bundle/release/*.aab
                    if-no-files-found: error

    sign:
        name: Sign
        runs-on: ubuntu-latest
        timeout-minutes: 10
        needs: build
        steps:
            -   name: Download unsigned APK
                uses: actions/download-artifact@v3
                with:
                    name: release-unsigned.apk
                    path: app/build/outputs/apk/release

            -   name: Download unsigned AAB
                uses: actions/download-artifact@v3
                with:
                    name: release-unsigned.aab
                    path: app/build/outputs/bundle/release

            -   name: Sign APK
                uses: r0adkll/sign-android-release@v1
                id: sign_apk
                with:
                    releaseDirectory: app/build/outputs/apk/release
                    signingKeyBase64: ${{ secrets.SIGNING_KEY }}
                    alias: ${{ secrets.KEY_ALIAS }}
                    keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
                    keyPassword: ${{ secrets.KEY_PASSWORD }}

            -   name: Sign AAB
                uses: r0adkll/sign-android-release@v1
                id: sign_aab
                with:
                    releaseDirectory: app/build/outputs/bundle/release
                    signingKeyBase64: ${{ secrets.SIGNING_KEY }}
                    alias: ${{ secrets.KEY_ALIAS }}
                    keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
                    keyPassword: ${{ secrets.KEY_PASSWORD }}

            -   name: Upload signed APK
                uses: actions/upload-artifact@v2
                with:
                    name: release-signed.apk
                    path: ${{ steps.sign_apk.outputs.signedReleaseFile }}

            -   name: Upload signed AAB
                uses: actions/upload-artifact@v2
                with:
                    name: release-signed.aab
                    path: ${{ steps.sign_aab.outputs.signedReleaseFile }}

    upload_to_firebase:
        name: Upload to Firebase
        runs-on: ubuntu-latest
        timeout-minutes: 10
        needs: [ build, sign ]
        steps:
            -   name: Checkout the code
                uses: actions/checkout@v3

            -   name: Download signed APK
                uses: actions/download-artifact@v3
                with:
                    name: release-signed.apk
                    path: app/build/outputs/apk/release

            -   name: Download signed AAB
                uses: actions/download-artifact@v3
                with:
                    name: release-signed.aab
                    path: app/build/outputs/bundle/release

            -   name: Upload signed APK to Firebase App Distribution
                uses: wzieba/Firebase-Distribution-Github-Action@v1
                with:
                    appId: ${{ secrets.FIREBASE_APP_ID }}
                    token: ${{ secrets.FIREBASE_TOKEN }}
                    file: app/build/outputs/apk/release/release-signed.apk

            -   name: Upload signed AAB to Firebase App Distribution
                uses: wzieba/Firebase-Distribution-Github-Action@v1
                with:
                    appId: ${{ secrets.FIREBASE_APP_ID }}
                    token: ${{ secrets.FIREBASE_TOKEN }}
                    file: app/build/outputs/bundle/release/release-signed.aab
